### ISSUE TITLE
basic-unbound

### ISSUE THREAD

**Issue by suricloud** [serverless-dns/serverless-dns#189]
Hi,

On my cloudflare worker i see now 2 workers created by serverless dns
1. serverless-dns
2. basic-unbound

Is this normal or a bug ?
And if ok, for what is the basic-unbound created.

**Comment by ignoramous** [comment]
basic-unbound is created because by *automated deploys* (#171) that we enabled for our own serverless-dns deploys. Also, make sure to disable automated deploys, if you don't need basic-unbound.

If you prefer to use basic-unbound, then make sure to edit `wrangler.toml` of your fork to fit in routes for the zones you own.
