### ISSUE TITLE
Node: Restore TLS sessions where possible

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#30]
nodejs docs: https://archive.md/FDXpt#tls_session_resumption

background: https://archive.md/fBwt5

**Comment by amithm7** [comment]
Current deployment supports both TLS v1.2 & v1.3. Session resumption (via session tickets) already works when the client uses TLS v1.2.

## Session Resumption on TLS v1.2

### Using Session Tickets

- NodeJS: :heavy_check_mark: Works
	- Session tickets are sent during handshake and reconnecting resumes session.
	- Example with current live deployment:
		```
		openssl s_client -connect 213.188.218.85:853 -reconnect -servername max.rethinkdns.com \
		-tls1_2 | grep -E "^(New|Reused)"
		```
- Deno: :heavy_check_mark: Works

### Using Session IDs

> Not explored

## Session Resumption on TLS v1.3

### Using Session Tickets (PSK)

- Spec: https://www.rfc-editor.org/rfc/rfc8446#section-2.2
- NodeJS :confused:
	- Two (different) session tickets are sent post handshake.
	- Unsupported? https://github.com/nodejs/node/issues/39691
- Deno: :confused:
	- One session ticket is sent post handshake.
- Unable to test properly due to openssl client bug: https://github.com/openssl/openssl/issues/10714

### Using Session IDs

> Implementation problems...

## 0-RTT on TLS v1.3

- NodeJS :skull: 
	- https://github.com/nodejs/node/issues/28931

**Comment by ignoramous** [comment]
@amithm7 This is done, I guess. Commit?

**Comment by amithm7** [comment]
This is built-in. There is a debug log here to test : https://github.com/serverless-dns/serverless-dns/blob/bc6dc503f1aa59b84c8fca29c801ca7c8bff75c9/src/server.js#L245-L247

**Comment by ignoramous** [comment]
So, nothing to do?

**Comment by ignoramous** [comment]
session resumption was recently removed due to memory reqs: https://github.com/serverless-dns/serverless-dns/commit/abf20c838ae42e5ba4cf856f5a29784bcf8be161

instead, tls (client) tickets are now valid for 7d: https://github.com/serverless-dns/serverless-dns/commit/20425bf48f9f01384ac47152f0a29c9901b6d9f2 and generated from the same seed across the entire fleet https://github.com/serverless-dns/serverless-dns/commit/0dcf5cf77bda216564017ffc8414ad148a14e32f
