### ISSUE TITLE
Configure Blocklist using Deno-Deploy

### ISSUE THREAD

**Issue by knsim24** [serverless-dns/serverless-dns#53]
![image](https://user-images.githubusercontent.com/95121651/151306295-42198ac7-9b7e-45f4-8f5b-7dbc8b6067b6.png)
Summary:
1. No issues for latency (25-50ms. Great)
2. No issues for error in deno-deploy (Great)
3. Config blocklist issues (syntax error- on website)
4. No issues on blocklist on deno-deploy (Great)

**Comment by ignoramous** [comment]
Deno's at 20ms latency? Wow. That's 3x faster than Workers on average. May be Deno keeps the isolate / process around a _lot_ longer than Cloudflare does.

Re: Configure blocklists: We've fixed that now. The rethinkdns configure webpage, which downloads the blocklist-metadata (json) from our servers, had issue dealing with the `content-disposition` http-header (typically used to show "save as" dialogs for downloads)... We've since change the way we "stream" the response to the clients a bit, and the webpage seems happy now.
