### ISSUE TITLE
Can you provide IP addresses in addition to the DoH/DoT templates?

### ISSUE THREAD

**Issue by ghost** [serverless-dns/serverless-dns#84]
I want to use DoH or DoT on Windows 11 but [your website](https://rethinkdns.com/configure) only gives me the URL, no IP address.

DNS servers always should be identified by IP address with other metadata such as DoH templates and DoT hostnames provided in addition. This is to avoid the security shortcomings posed by the chicken and egg problem with using hostname-based DNS: what DNS server are you trusting to look up the IP address of your trusted DNS server?

**Comment by ignoramous** [comment]
> I want to use DoH or DoT on Windows 11 but [your website](https://rethinkdns.com/configure) only gives me the URL, no IP address.

Interesting. We should give out IP addresses for `max.rethinkdns.com` even if not for `sky.rethinkdns.com` (which is *serverless*).

---

Only the servers hosted on Fly.io at `max.rethinkdns.com` have a stable IP which are

```
137.66.7.89
2a09:8280:1::3:6e18
```

The servers on Cloudflare.com at `sky.rethinkdns.com` do not have a stable IP, but the current ones are:

```
104.21.10.13
172.67.162.27
2606:4700:3033::ac43:a21b
2606:4700:3034::6815:a0d
```

You can always find these by querying from a website like `dohjs.org`.

---

> 1: This is to avoid the security shortcomings 

This isn't a security issue, since a bogus IP will never have TLS certs for `max` or `sky`.

> 2: posed by the chicken and egg problem

That it is, but DNS is a hierarchical and a federated system of names. Fetching the IP address from another DNS endpoint (such as the underlying network) is okay, in my opinion.

> 3: ...what DNS server are you trusting to look up the IP address of your trusted DNS server?

Please #1 above. This isn't a security issue. It is however a privacy issue (in one sense).
